require:
  - rubocop-rails
  - rubocop-performance
  - rubocop-rspec

AllCops:
  TargetRubyVersion: "3.3.1"
  Exclude:
    - "db/**/*"
    - "config/**/*"
    - "script/**/*"
    - "bin/{rails,rake}"
    - "bin/bundle"
    - "app/helpers"
    - "spec/helpers"
    - !ruby/regexp /old_and_unused\.rb$/
  NewCops: enable

Layout/LineLength:
  Max: 100
Metrics/AbcSize:
  CountRepeatedAttributes: false
Metrics/ClassLength:
  Enabled: false
Metrics/MethodLength:
  Enabled: false
Rails/I18nLocaleTexts:
  Enabled: false
RSpec/ExampleLength:
  Enabled: false
RSpec/MultipleExpectations:
  Enabled: false
Style/Documentation:
  Enabled: false
Style/ParallelAssignment:
  Enabled: false
