version: "3.8"
services:
  web:
    platform: linux/amd64
    build:
      context: .
      args:
        UID: ${UID:-1000}
        GID: ${GID:-${UID:-1000}}
    ports:
      - "80:80"
    env_file:
      - .env/development/web
      - .env/development/database
    deploy:
      resources:
        limits:
          memory: 1G

  database:
    platform: linux/amd64
    image: postgres
    env_file:
      - .env/development/database
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  db_data:
